### ISSUE TITLE
Multiple ID's or segments before URI

### ISSUE THREAD

**Issue by barhaleacct** [Osedea/angular-osd-resource#1]
Hi.
I'm absolutely loving this app. People really need to understand that for a large scale app this is absolutely amazing.

In my current project to pull various data I had to create a shed load of functions in a data factory.
Then I needed a codeigniter controller with a load of functions to handle the calls. Now I'm creating one controller (api) with one function and within that aquery to call the data depending on the relationship, per old controller i.e. function child, function invoices, functions documents, and then depending on the URI segment uri segment 4 which is where your relationship usually sends.
I.e.
Www webaddress.co.uk/index.php/api/child/12/class
Or same /12/invoices 
I'm doing the same as a function did before

Now I can just add relationships and the function is auto created.
And I can just use what I need and keep better track 

A have a few things though.. I've tried submitting multiple ID's. I.e. I may need to send an ID for a person and and ID for a class at the same time as URI segments I.e. API/person/12/15/classes rather than 2 queries to get the same info. 
To return that person and that class. But I've not been able to work it out so far
Or send multiple relationships at a time
I.e
Child/12/15/class/17/invoice
To return the class 15 detail for child 12 and invoice 17. 
It's not a massive thing as in its current state it's absolutely superb. Just maybe needs a bit more fleshing out around the methods and sending multiple data.....
How would I send a serialised form with the post functionality?

Just me likely being tired, plus I'm currently on tramadol and diazepam for back pain and not quite yet fully understanding. 
So more queries than issues. But I'm making several large scale applications and can do a lot of testing and helping. (Company intranet for 700 people) and a membership registration and payment gateway with several hundred users.
I've already transferred around 100 functions in a day. That would have taken me 5-10 days previously. I pull multiple days from over 200 database tables.
I've also reconfigured our app on the iOS store (built using ionic) to pull data using this rather than factory and see speed increases across the board. 
Any help would be good. Sorry to rant on but you've got something great on your hands here.

**Comment by barhaleacct** [comment]
If you need any more clarification let me know, as I'd also like to be able to submit a key with a query.
I.e a validation key that confirms an API request is from a trusted approved source.

**Comment by barhaleacct** [comment]
I suppose along with submitting serialised data I'm talking about having a different way of having

.add('Form', '/api/forms/:id')
So you can use as with multiple /:id/:id
add('Form', '/api/forms/:id/:id/param/:id')

Using either or on the fly

**Comment by damacisaac** [comment]
Thank you for your comment! I'm happy to hear someone finds it useful. I'm going to answer quickly for now and take a closer look later.

For querying a route with multiple ids, you would have to give them different names:

`.add('Form', '/api/forms/:form_id/:next_id/:document_id')`

and then query with:

`Form.query({ form_id: 1, next_id: 2, document_id: 3, query_param: 'test' });`

**Comment by damacisaac** [comment]
If I understand correctly, to send a serialized form you just need to pass it through in the save() function and it will end up in the request body:

var serializedForm = '...';
`Form.save({ form: serializedForm }).then();`

**Comment by barhaleacct** [comment]
Would having

``` javascript
.add('Form', '/api/forms/:form_id/:next_id/:document_id')
```

Mean that if using "Form" in the controller and I didn't always want to send multiple ID's
e.g.
I may want just a form so send 

``` javascript
Form.query({ form_id: 1}).then();
```

or i may want a form and comments from a specific person only so might only want to send 2 ID's

``` javascript
Form.query({ form_id: 1,user_id: 2}).then();
```

Maybe now I have more time to explain myself!!

**Comment by barhaleacct** [comment]
Thank You on the serialzedForm aspect. Wasn't sure if it would sent it - should have just tested it to be honest! Better to ask though!

You really have something cool here, really does trump the whole resolve first aspect for me due to the whole relations saving you typing multiple queries.

**Comment by damacisaac** [comment]
For sending a variable number of IDs, angular will automatically strip any trailing slashes in the route. This means that you can pass only `form_id` if you need to.

**Comment by barhaleacct** [comment]
Smashing.

And is there anyway to chose a way to adjust the post headers to.
    headers : { 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8' }

**Comment by damacisaac** [comment]
you'll have to create a custom method and specify the headers on it. see the usage section for $resource, under the action parameter:

https://docs.angularjs.org/api/ngResource/service/$resource
